# Generated by Django 2.0.4 on 2018-04-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contactPref', models.CharField(choices=[('p', 'Phone'), ('e', 'Email'), ('f', 'Facebook')], max_length=1)),
                ('studentType', models.CharField(choices=[('n', 'New'), ('o', 'Old')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='studentID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
