# Generated by Django 2.0.4 on 2018-04-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contactPref', models.CharField(choices=[('p', 'Phone'), ('e', 'Email'), ('f', 'Facebook')], max_length=1)),
                ('payScale', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('bsb', models.IntegerField()),
                ('accountNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('lessonType', models.CharField(max_length=100)),
                ('lessonDuration', models.IntegerField()),
                ('lessonCost', models.IntegerField()),
                ('totalNumberOfLessons', models.IntegerField()),
                ('totalLessonCost', models.IntegerField()),
                ('studentID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('quality', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('rentalPrice', models.IntegerField()),
                ('salePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('studentID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contactPref', models.CharField(choices=[('p', 'Phone'), ('e', 'Email'), ('f', 'Facebook')], max_length=1)),
                ('payScale', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('bsb', models.IntegerField()),
                ('accountNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contactPref', models.CharField(choices=[('p', 'Phone'), ('e', 'Email'), ('f', 'Facebook')], max_length=1)),
                ('payScale', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('bsb', models.IntegerField()),
                ('accountNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('studentID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNumber', models.IntegerField()),
                ('streetName', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contactPref', models.CharField(choices=[('p', 'Phone'), ('e', 'Email'), ('f', 'Facebook')], max_length=1)),
                ('payScale', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('bsb', models.IntegerField()),
                ('accountNumber', models.IntegerField()),
                ('schoolID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.School')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='teacherID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='teacherID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='manager',
            name='schoolID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.School'),
        ),
        migrations.AddField(
            model_name='language',
            name='teacherID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='instrumenthire',
            name='lessonID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Lesson'),
        ),
        migrations.AddField(
            model_name='instrumenthire',
            name='studentID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='contract',
            name='teacherID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.School'),
        ),
    ]
