# Generated by Django 2.0.5 on 2018-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('quality', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('rentalPrice', models.IntegerField()),
                ('salePrice', models.IntegerField()),
            ],
        ),
    ]
