# Generated by Django 2.0.5 on 2018-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='available',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='rentalPrice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='salePrice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
