# Generated by Django 2.0.5 on 2018-05-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentmanagement', '0002_auto_20180523_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='available',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='rentalPrice',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='salePrice',
        ),
        migrations.AddField(
            model_name='instrument',
            name='assigned_student',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='rental_price',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='instrument',
            name='sale_price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='quality',
            field=models.CharField(choices=[('n', 'New'), ('u', 'Used'), ('p', 'Unspecified')], default='p', max_length=2),
        ),
    ]
