# Generated by Django 2.0.5 on 2018-05-30 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_accepted', models.BooleanField(default=False)),
                ('student_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('C', 'Completed')], default='P', max_length=1)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Contract Start Date')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
